### ISSUE TITLE
Unable to gem install plugin

### ISSUE THREAD

**Issue by sidprak** [y-ken/fluent-plugin-pagerduty#1]
I receive the following error when I try to install this plugin. Is the plugin still published? I've also tried using `fluent-gem` to install and run into the same error.

```bash
gem install fluent-plugin-pagerduty
ERROR:  Could not find a valid gem 'fluent-plugin-pagerduty' (>= 0) in any repository
ERROR:  Possible alternatives: fluent-plugin-tagdata, fluent-plugin-tagged_udp, fluent-plugin-arduino, fluent-plugin-assert, fluent-plugin-dedup
```

**Comment by y-ken** [comment]
This plugin does not released yet. Please use pagerduty from another tools like datadog.
I have started to implement before, it does not successed due to the pagerduty gem error.
```
2017-03-14 18:31:21 +0900 [error]: #0 pagerduty: request failed.  error_class=Net::HTTPServerException error="400 \"Bad Request\""
```

**Comment by y-ken** [comment]
Hi #2 has merged.
But, Does it work on you environment?

Would you please check the behavior?

## test step

```
# git clone or your working directory
$ git clone https://github.com/y-ken/fluent-plugin-pagerduty.git
$ cd fluent-plugin-pagerduty
$ bundle install --path vendor/bundle
$ bundle exec fluentd -c fluent.conf
```

```
$ cat fluent.conf
<source>
  @type forward
</source>

<match notify.*>
  @type pagerduty
  service_key ******
</match>
```

```
$ echo '{"description":"something error","details":"abc"}' | bundle exec fluent-cat notify.pagerduty
```

## how to get api key
![fluent-plugin-pagerduty_api_page1](https://cloud.githubusercontent.com/assets/1734549/24068038/946da316-0bc8-11e7-883b-13c846943121.png)
![fluent-plugin-pagerduty_api_page2](https://cloud.githubusercontent.com/assets/1734549/24068040/ac2ab502-0bc8-11e7-9b27-6005731d8ecf.png)

**Comment by sidprak** [comment]
Yes, it works for my environment but we integrate it using a service token rather than a user token. See screenshot:
<img width="1025" alt="screenshot 2017-03-18 18 20 43" src="https://cloud.githubusercontent.com/assets/1428486/24077350/ab9f9dd4-0c07-11e7-9f9f-8cd27a451b6e.png">

**Comment by y-ken** [comment]
I got why I had failed to run it.

**Comment by y-ken** [comment]
I've released it now! Would you please try it on?
https://rubygems.org/gems/fluent-plugin-pagerduty

**Comment by sidprak** [comment]
@y-ken it works! It's installed in my environment now. Thank you!

**Comment by y-ken** [comment]
Sounds great!
